"""Updated Message model to specify foreign key constraints

Revision ID: 18c6c0ef8d93
Revises: 8e5709954c45
Create Date: 2024-09-10 00:07:09.294236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c6c0ef8d93'
down_revision = '8e5709954c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
